gemini:
  max_file_size_mb: 5
  model_name: "gemini-1.5-flash"
  batch_size: 3
  max_concurrent: 1

database:
  default_path: "data/embeddings.db"
  min_similarity: 0.6

bot:
  name: "Dr. Sedman"
  role: "Sedimentologist"
  model_name: "meta-llama/Llama-3.2-3B-Instruct"
